### ISSUE TITLE
Resolve shortened article URLs

### ISSUE THREAD

**Issue by tuxpiper** [project-pheme/project-pheme-data-interface#6]
Follow HTTP redirections until (hopefully) reaching the canonical URL with the actual article

**Comment by tuxpiper** [comment]
@tuxpiper Get timeframes for usaar and onto to see what is feasible to have by the eval

**Comment by lauratolosi** [comment]
So I was surprised to find that one can use such command line in Linux:
curl -sIL <website> | grep ^Location

Since I am at the moment on Windows 10, I had to install CURL and call it like this:
curl -sIL bloom.bg/2bsbDv3  
In the output, I see Location: http://www.bloomberg.com/news/articles/2016-08-15/how-hyperloop-one-went-off-the-rails

Will test on Linux tomorrow.

**Comment by tuxpiper** [comment]
URLs are shortened now, although since this is made in the dashboard, it can cause significant delays when first loading details from a Pheme (happens when you have a lot of articles).

Closing this one and reopening now that asks the canonical resolved URLs to be found out and stored within the pipeline/graphdb. To be prioritized.
